### ISSUE TITLE
[Suggestion] Add ability to remove Drops

### ISSUE THREAD

**Issue by AmeerReal** [SchdowNVIDIA/OreEarn#1]
Can you add the ability to remove drops?
Like when its true nothing goes to your inventory when you mine or drops and when its false everything goes to your inventory or the mined things drops

**Comment by AlexPads** [comment]
Yeah this would be cool 👍

**Comment by justin-eckenweber** [comment]
Hey, sorry for the late answer.
So you want an option to disable ore drops? So nothing gets dropped?
For specific worlds or global?

**Comment by AmeerReal** [comment]
Yeah, it doesn't matter
If you want make it global then improve it in the next version and make it to specific worlds.

**Comment by justin-eckenweber** [comment]
Okay, I'm working on it :)

**Comment by justin-eckenweber** [comment]
# Added
Feature added in OreEarn 1.7.0
