### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by JaxkDev** [SchdowNVIDIA/OreEarn#3]
Nice plugin first off.

But one small thing is dependencies, they aren't specified on poggit or plugin.yml only readme 
I would suggest adding it to both poggit and plugin.yml and running a check onEnable to stop errors occuring here `$this->getServer()->getPluginManager()->getPlugin("EconomyAPI")` that would return null if it doesn't exist, maybe disable plugin if null.

**Comment by justin-eckenweber** [comment]
Oh, you're right. I'm adding it to the next version! Thank you :)

**Comment by JaxkDev** [comment]
No problem, good plugin 👍

**Comment by justin-eckenweber** [comment]
Added in OreEarn Update 1.8.1 thank you!
