### ISSUE TITLE
Incompatibility with Factions plugins

### ISSUE THREAD

**Issue by DenielWorld** [SchdowNVIDIA/OreEarn#4]
If an ore is mined in a claimed area of a faction, the ore does not break but the player still earns money. Since this plugin is used mostly for faction servers I believe that compatibility with the faction plugins would be helpful (At least with the basic faction plugin FactionsPro). Thanks, great plugin.

**Comment by justin-eckenweber** [comment]
Well, that's not possible.
Are you sure you're using the newest version?

**Comment by DenielWorld** [comment]
Yes. When you mine an ore in a claimed area, you get the money but the block doesn't break so it is an infinite source.

**Comment by justin-eckenweber** [comment]
Well, there was an issue like that on OreEarn ~1.3. I will look into it very soon, but I have to do many things at the moment.

**Comment by DenielWorld** [comment]
Ok, thanks

**Comment by justin-eckenweber** [comment]
Well this issue is maybe because of Factions is "too slow" to stop the event. So OreEarn is faster and doing the Reward task. Maybe i can do an extra branch for this but it will take a while to fix that for factions. Which Factions plugin are you using?

**Comment by justin-eckenweber** [comment]
No response.
